
language: cpp

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update
  - sudo apt-get install -y libhiredis-dev libev-dev cmake

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


jobs:
  include:

    - stage: build
      script:
        - make

    - stage: build docker
      script:
        - cd docker
        - docker build --rm --no-cache --tag docker-cm-icinga2-checks .
